### ISSUE TITLE
Setup.py uses a removed `pypandoc.convert` method

### ISSUE THREAD

**Issue by xlucn** [joshspeagle/dynesty#492]
** Dynesty version **
2.1.4. From Arch Linux's AUR package, which builds and installs with source files.

**Describe the bug**
During build (`python -m build --wheel --no-isolation`), I run into an error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
    main()
    ~~~~^^
  File "/usr/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
                             ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
    self.run_setup()
    ~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 516, in run_setup
    super().run_setup(setup_script=setup_script)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 318, in run_setup
    exec(code, locals())
    ~~~~^^^^^^^^^^^^^^^^
  File "<string>", line 24, in <module>
AttributeError: module 'pypandoc' has no attribute 'convert'
```
Which points to this line in code:
https://github.com/joshspeagle/dynesty/blob/55d93d00231d6eb8d8ddc534416ea7f1de8a2944/setup.py#L24

This `pypandoc.convert` method was removed (see https://github.com/JessicaTegner/pypandoc/commit/3e296b711463c0df7b1b387b4d2187ce283e200b#diff-260af425b84a1eb4003b6bd017e57110226490652c6e97633dc33ce75359face), and thus the code here needs a fix as well.

**Setup**
Irrelevant, this is a installation issue.

** Dynesty output **
Irrelevant, this is a installation issue.

**Bug**

**Additional context**
I guess most users don't have pypandoc installed thus haven't run into this issue. And I have pypandoc installed recently thus haven't run into it until now.

**Comment by xlucn** [comment]
I find this easy to fix. I will come up with a PR soon.
