### ISSUE TITLE
singular decomposition

### ISSUE THREAD

**Issue by joshspeagle** [joshspeagle/dynesty#78]
Both @guillochon and @catherinezucker have reported singular decomposition errors when running. I thought I had fixed this, but clearly it's still happening (although much less often than before).

**Comment by joshspeagle** [comment]
I think I've fixed this by moving to a simpler scheme to keeping the relevant matrices positive-definite. Let me know if there are any future issues after updating to v0.8.4.

**Comment by joshjchayes** [comment]
Hi, a bit of necromancy here, but I'm getting errors reading 
numpy.linalg.LinAlgError: 58th leading minor of the array is not positive definite

The error is being thrown by the cholesky functions.

Is this a known error, and how might I go about fixing this? The problem I am attempting to solve is 58-dimensioned, which makes me wonder about the significance of the 58th leading minor.

**Comment by joshspeagle** [comment]
It is, and has been raised in #140. As discussed there, in theory, this should not be happening since I have a bunch of safety checks to try and raise the matrix's condition number (which appear to be failing). Do you have a traceback indicating where exactly this issue arises?

**Comment by joshjchayes** [comment]
Hi Josh, Many thanks for replying. Here is the traceback of the error:

Beginning retrieval of 58 parameters
51123it [1:58:00,  7.23it/s, bound: 201 | nc: 25 | ncall: 1270896 | eff(%):  4.023 | loglstar:   -inf < -75637.690 <    inf | logz: -75897.150 +/-  1.606 | dlogz: 700.246 >  0.209]  
Traceback (most recent call last):
  File "fitting_script.py", line 24, in <module>
    detrending='quadratic', nlive=200, ld_model='quadratic')
  File "/data/jhayes/anaconda3/lib/python3.7/site-packages/transitfit-0.6.1-py3.7.egg/transitfit/_pipeline.py", line 128, in run_retrieval_from_paths
  File "/data/jhayes/anaconda3/lib/python3.7/site-packages/transitfit-0.6.1-py3.7.egg/transitfit/retriever.py", line 131, in run_dynesty
  File "/data/jhayes/anaconda3/lib/python3.7/site-packages/dynesty-1.0.0-py3.7.egg/dynesty/sampler.py", line 908, in run_nested
    add_live=add_live)):
  File "/data/jhayes/anaconda3/lib/python3.7/site-packages/dynesty-1.0.0-py3.7.egg/dynesty/sampler.py", line 738, in sample
    bound = self.update(pointvol)
  File "/data/jhayes/anaconda3/lib/python3.7/site-packages/dynesty-1.0.0-py3.7.egg/dynesty/nestedsamplers.py", line 563, in update
    pool=pool)
  File "/data/jhayes/anaconda3/lib/python3.7/site-packages/dynesty-1.0.0-py3.7.egg/dynesty/bounding.py", line 585, in update
    firstell = bounding_ellipsoid(points, pointvol=pointvol)
  File "/data/jhayes/anaconda3/lib/python3.7/site-packages/dynesty-1.0.0-py3.7.egg/dynesty/bounding.py", line 1363, in bounding_ellipsoid
    ell = Ellipsoid(ctr, covar)
  File "/data/jhayes/anaconda3/lib/python3.7/site-packages/dynesty-1.0.0-py3.7.egg/dynesty/bounding.py", line 152, in __init__
    self.axes = lalg.cholesky(cov, lower=True)  # transformation axes
  File "/data/jhayes/anaconda3/lib/python3.7/site-packages/scipy/linalg/decomp_cholesky.py", line 91, in cholesky
    check_finite=check_finite)
  File "/data/jhayes/anaconda3/lib/python3.7/site-packages/scipy/linalg/decomp_cholesky.py", line 40, in _cholesky
    "definite" % info)
numpy.linalg.LinAlgError: 58-th leading minor of the array is not positive definite

**Comment by joshspeagle** [comment]
Oh -- that is a new one. I don't think I set up a separate check for the Cholesky decomposition; I just assumed that the pseudo-inverse calculations would take care of those. Let me re-open this and see about adding that in.

Outside of this particular problem, I'm not sure I can recommend `dynesty` for sampling such a large parameter space. Hopefully it's working for you, but that's definitely beyond the scope of where I'd say it's designed to work well ;).
